### ISSUE TITLE
Enable the FLUCATS study to run on EMIS

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/backends#2]
The study in question is https://jobs.opensafely.org/staff/applications/5e3e/ and was approved by Amir in May.

@LFISHER7 is our main contact at the moment and has said that the study will be ready in the next couple of weeks.

~It looks like EMIS have switched off SSH access, so we'll need to contact tech support in the first instance (unless Simon's already done that). Then, investigate what else, if anything, may not be working.~

It appears that job-server is hearing back from job-runner on EMIS, so the backend is probably up. Need to establish whether the database is ready to be queried next.

See [slack conversation](https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1659015663646839)

**Comment by bloodearnest** [comment]
VM IP had changed. For future reference, we can see what the IP currently is by looking at access logs from job-server. I updated emis.opensafely.org to point the new IP.

My certificate had been revoked, presumably explicitly when we stopped using it. Generated a new certificate/key, uploaded, restarted, and  seems to be working.

Minor doc updates as a result: https://github.com/ebmdatalab/team-manual/pull/289
